Update docker-deploy.yml

diff --git a/.github/workflows/docker-deploy.yml b/.github/workflows/docker-deploy.yml
--- a/.github/workflows/docker-deploy.yml
+++ b/.github/workflows/docker-deploy.yml
@@ -30,7 +30,7 @@ jobs:
         echo "Docker image pulled successfully."
 
         
-        docker run -d -p 80:80 --name my_nginx_container nginx || { echo "Docker run failed!"; exit 1; }
+        docker run -d -p 8080:80 --name my_nginx_container nginx || { echo "Docker run failed!"; exit 1; }
         
         echo "Docker container started successfully!"
         EOF
